### ISSUE TITLE
mailgun 异常反馈

### ISSUE THREAD

**Issue by JamCh01** [NimaQu/ss-panel-v3-mod_Uim#273]
配置mailgun之后使用 sendDiaryMail 进行发信测试的异常：
```
root@main:/www/wwwroot/mysite# php xcat sendDiaryMail
Send daily mail to user: 1PHP Fatal error:  Uncaught Mailgun\Connection\Exceptions\MissingEndpoint: The endpoint you've tried to access does not exist. Check your URL. in /www/wwwroot/mysite/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:133
Stack trace:
#0 /www/wwwroot/mysite/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /www/wwwroot/mysite/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('smtp.mailgun.or...', Array, Array)
#2 /www/wwwroot/mysite/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('smtp.mailgun.or...', Array, Array)
#3 /www/wwwroot/mysite/app/Services/Mail/Mailgun.php(42): Mailgun\Mailgun->sendMessage('smtp.mailgun.or...', Array, Array)
#4 /www/wwwroot/mysite/app/Services/Mail.php(69): App\Services\Mail\Mailgun->send('myemail@hotma...', 'mysite-\xE6\xAF\x8F\xE6\x97\xA5\xE6\xB5\x81...', '<!DOCTYPE html . in /www/wwwroot/mysite/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 133/RestClient.php on line 133
```

**Comment by NimaQu** [comment]
@JamCh01 你自己 id为1的用户邮箱有问题吗啊

**Comment by JamCh01** [comment]
没有问题，日常使用的邮箱 myemail 这里只是 fake…

**Comment by NimaQu** [comment]
那就是你参数不对

**Comment by JamCh01** [comment]
$System_Config['mailgun_key'] = 'key-\w{32}';
$System_Config['mailgun_domain'] = 'smtp.mailgun.org';
$System_Config['mailgun_sender'] = 'postmaster@domian';
目前配置的参数是这样的）

**Comment by NimaQu** [comment]
@JamCh01 domain 不对
