### ISSUE TITLE
dailyjob执行失败

### ISSUE THREAD

**Issue by kkren** [NimaQu/ss-panel-v3-mod_Uim#313]
```
$ php -n xcat dailyjob               

Fatal error: Uncaught Error: Class 'PDO' not found in /var/www/ss-panel-v3-mod_Uim/vendor/illuminate/database/Capsule/Manager.php:49
Stack trace:
#0 /var/www/ss-panel-v3-mod_Uim/vendor/illuminate/database/Capsule/Manager.php(37): Illuminate\Database\Capsule\Manager->setupDefaultConfiguration()
#1 /var/www/ss-panel-v3-mod_Uim/app/Services/Boot.php(39): Illuminate\Database\Capsule\Manager->__construct()
#2 /var/www/ss-panel-v3-mod_Uim/bootstrap.php(29): App\Services\Boot::bootDb()
#3 /var/www/ss-panel-v3-mod_Uim/xcat(4): require('/var/www/ss-pan...')
#4 {main}
  thrown in /var/www/ss-panel-v3-mod_Uim/vendor/illuminate/database/Capsule/Manager.php on line 49
```
phpinfo()中存在pdo
![default](https://user-images.githubusercontent.com/23287823/46257642-cc61f600-c4ef-11e8-852a-6ca7a99066b1.png)

```
$ php -v
PHP 7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35 (cli) (built: Sep 10 2018 10:05:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35, Copyright (c) 1999-2018, by Zend Technologies
```

系统是debian9

**Comment by kkren** [comment]
去掉-n参数后正常执行

**Comment by wewall** [comment]
666666

**Comment by mashirozx** [comment]
-n 参数有什么作用吗？作者的教程里专门强调了 -n 参数：<https://www.40huo.cn/blog/sspanel-mod.html>

**Comment by galaxychuck** [comment]
@mashirozx 不調用php參數執行命令

**Comment by mashirozx** [comment]
@galaxychuck 感谢回复。那就是说有没有 -n 参数执行的结果都是一致的吧？

**Comment by Anankke** [comment]
@mashirozx 作者没说过个，拿着个第三方博客说个锤子呢？

**Comment by galaxychuck** [comment]
@mashirozx 不加的話，可能會執行失敗

**Comment by mashirozx** [comment]
@galaxychuck 可是不加的时候会遇到相同的 `Class 'PDO' not found` 问题，请问这个还有什么处理方法吗？

@Anankke 那个教程是 [wiki](https://wiki.sspanel.host/) 上给的第一个链接，我以为是你的...

**Comment by Anankke** [comment]
@mashirozx wiki 的第一个链接不是你发的那个

**Comment by mashirozx** [comment]
@Anankke 当时发完就马上删了，不知道是不是贴错了。。我是说这个教程<https://blog.anank.ke/w/SSPanel_with_DROP_DATABASE_BT>

还想请问一下大大，我想自动清除这个页面的记录，dailyjob 可以实现吗？
![image](https://user-images.githubusercontent.com/16148054/66981877-a05be780-f0e7-11e9-9d60-8b931dd2adc8.png)

**Comment by galaxychuck** [comment]
@mashirozx 就是不加的時候才會出現該問題，也可安裝拓展解決
Class 'PDO' not found ：
yum(apt) install php-pdo
service php-fpm restart

**Comment by galaxychuck** [comment]
@mashirozx 請熟讀/app/Command/Job.php代碼並背誦

**Comment by mashirozx** [comment]
@galaxychuck `php -m` 里面显示有 PDO 的：
```
[PHP Modules]
···
PDO
pdo_mysql
···
```

`phpinfo()`：
![image](https://user-images.githubusercontent.com/16148054/66984038-807af280-f0ec-11e9-905b-742ffe67ae21.png)

我用的是ubuntu，尝试了安装 php-pdo，显示好像包已经集成在 php 里了：
```
m# apt  install php-pdo
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php-pdo is a virtual package provided by:
  php7.0-common 7.0.22-0ubuntu0.17.04.1
  php7.1-common 7.1.17-0ubuntu0.17.10.1
  php7.2-common 7.2.19-0ubuntu0.18.04.2
You should explicitly select one to install.

E: Package 'php-pdo' has no installation candidate

# php -v
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by mashirozx** [comment]
> @mashirozx 請熟讀/app/Command/Job.php代碼並背誦

非 PHP 玩家，代码没太看懂诶~

就想问下流量使用记录页（/admin/trafficlog）的记录也可以用 dailyjob 清除吗？（我跑了一下 `php xcat dailyjob`，记录还在的样子）

**Comment by wewall** [comment]
> > @mashirozx 請熟讀/app/Command/Job.php代碼並背誦
> 
> 非 PHP 玩家，代码没太看懂诶~

那您是什么玩家

**Comment by wewall** [comment]
> > @mashirozx 請熟讀/app/Command/Job.php代碼並背誦
> 
> 非 PHP 玩家，代码没太看懂诶~
> 
> 就想问下流量使用记录页（/admin/trafficlog）的记录也可以用 dailyjob 清除吗？（我跑了一下 `php xcat dailyjob`，记录还在的样子）

`php xcat dailyjob ` 可以清除，具体看 job.php 逻辑

**Comment by galaxychuck** [comment]
@wewall 渣男進群水

**Comment by wewall** [comment]
引领时尚潮流的钱爸来了

**Comment by mashirozx** [comment]
> > > @mashirozx 請熟讀/app/Command/Job.php代碼並背誦
> > 
> > 
> > 非 PHP 玩家，代码没太看懂诶~
> 
> 那您是什么玩家

LOL玩家
[![1500639940723.gif](https://view.moezx.cc/images/2017/11/25/1500639940723.gif)](https://view.moezx.cc/image/fUiQ)

**Comment by mashirozx** [comment]
> > > @mashirozx 請熟讀/app/Command/Job.php代碼並背誦
> > 
> > 
> > 非 PHP 玩家，代码没太看懂诶~
> > 就想问下流量使用记录页（/admin/trafficlog）的记录也可以用 dailyjob 清除吗？（我跑了一下 `php xcat dailyjob`，记录还在的样子）
> 
> `php xcat dailyjob ` 可以清除，具体看 job.php 逻辑

具体是这条实现的吗？<https://github.com/galaxychuck/ss-panel-v3-mod_UIChanges/blob/dev/app/Command/Job.php#L136>

**Comment by mashirozx** [comment]
> > 具体是这条实现的吗？https://github.com/galaxychuck/ss-panel-v3-mod_UIChanges/blob/dev/app/Command/Job.php#L136
> 
> 是

感谢
