### ISSUE TITLE
后端安装错误，无法对接

### ISSUE THREAD

**Issue by MAOGE2018** [NimaQu/ss-panel-v3-mod_Uim#85]
参考教程：
https://www.you12580.us/sspanel-mod-%E9%AD%94%E6%94%B9%E7%89%88-%E4%BA%8C%E6%AC%A1%E4%BF%AE%E6%94%B9%E7%89%88%E5%90%8E%E7%AB%AF%E6%90%AD%E5%BB%BA%E6%95%99%E7%A8%8B-%E5%90%8E%E7%AB%AF%E8%BF%9C%E7%A8%8B%E8%8A%82%E7%82%B9.html

以下是错误
[root@vultr shadowsocks]# python server.py
loaded collections.OrderedDict
IPv6 support
INFO: ShadowsocksR 3.4.0 mod by esdeathlove
INFO: current process RLIMIT_NOFILE resource: soft 1024 hard 4096
INFO: loading config from user-config.json
2018-05-17 21:47:44 ERROR    auto_block.py:293 Traceback (most recent call last):
  File "/root/shadowsocks/auto_block.py", line 289, in thread_db
    db_instance.auto_block_thread()
  File "/root/shadowsocks/auto_block.py", line 70, in auto_block_thread
    charset='utf8')
  File "/usr/lib/python2.7/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '198.13.32.244' (113)")

2018-05-17 21:47:44 INFO     util.py:49 loading libcrypto from libcrypto.so.10
2018-05-17 21:47:44 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2018-05-17 21:47:44 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2018-05-17 21:47:44 ERROR    db_transfer.py:870 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 862, in thread_db
    db_instance.push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 288, in push_db_all_user
    self.update_all_user(dt_transfer)
  File "/root/shadowsocks/db_transfer.py", line 79, in update_all_user
    charset='utf8')
  File "/usr/lib/python2.7/site-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '198.13.32.244' (113)")

^CTraceback (most recent call last):
  File "server.py", line 78, in main
    threadMain.join(10.0)
  File "/usr/lib64/python2.7/threading.py", line 962, in join
    self.__block.wait(delay, balancing)
  File "/usr/lib64/python2.7/threading.py", line 362, in wait
    _sleep(delay)
KeyboardInterrupt

[root@vultr shadowsocks]#

**Comment by MAOGE2018** [comment]
大概部署是这样
两台 vps 
各自都安装了宝塔
vps-vip1（后端）
vps-vip5  （web+后端）
![qq 20180517215725](https://user-images.githubusercontent.com/39059232/40181909-cc141cc0-5a1c-11e8-8629-ab831ece960b.png)
同样方法安装。
